# Generated by Django 5.1.3 on 2024-11-11 10:45

import django.core.validators
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalApiResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Transaction ID')),
                ('response_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'External API Response',
                'verbose_name_plural': 'External API Responses',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('999.99'))], verbose_name='Preço total')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Completo'), ('failed', 'Falhou'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', max_length=10, verbose_name='Estado do pagamento')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Nome do Cliente')),
                ('payment_type', models.CharField(choices=[('user_balance', 'Saldo do Usuário'), ('credit_card', 'Cartão de Crédito'), ('paypal', 'PayPal'), ('bank_transfer', 'Transferência Bancária')], default='user_balance', max_length=100, verbose_name='Tipo de pagamento')),
            ],
            options={
                'verbose_name': 'Método de pagamento',
                'verbose_name_plural': 'Métodos de pagamento',
            },
        ),
        migrations.CreateModel(
            name='PaymentPromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Promotion Code',
                'verbose_name_plural': 'Payment Promotion Codes',
            },
        ),
    ]
