# Generated by Django 5.1.3 on 2024-11-11 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_initial'),
        ('payments', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='payments.externalapiresponse', verbose_name='External API Response'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod', verbose_name='Método de pagamento'),
        ),
        migrations.AddField(
            model_name='paymentpromotioncode',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_codes', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentpromotioncode',
            name='promotion_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.promotioncode'),
        ),
        migrations.AddField(
            model_name='payment',
            name='used_coupons',
            field=models.ManyToManyField(blank=True, related_name='payments', through='payments.PaymentPromotionCode', to='products.promotioncode', verbose_name='Cupons aplicados'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['payment_type'], name='payments_pa_payment_c8697a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['name'], name='payments_pa_name_4bafbe_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentpromotioncode',
            index=models.Index(fields=['payment', 'promotion_code'], name='payments_pa_payment_44ef51_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer'], name='payments_pa_custome_e35aff_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payments_pa_order_i_1d1c93_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['modified'], name='payments_pa_modifie_b3c796_idx'),
        ),
    ]
