# Generated by Django 5.1 on 2024-09-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'cargo', 'verbose_name_plural': 'cargos'},
        ),
    ]
