# Generated by Django 5.1.3 on 2024-11-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='status_changed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
