# Generated by Django 5.1.3 on 2024-11-11 10:45

import django.core.validators
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('position', models.IntegerField(db_index=True, help_text='(Obrigatório, não podendo ser igual a nenhum outro) Posição em que o conteúdo ficará, começando do menor (parte superior da página) para o maior (parte inferior da página).', unique=True, verbose_name='Posição')),
                ('image_cima', models.ImageField(blank=True, help_text='Imagem que caso tiver, aparecerá em cima do título.', upload_to='about/cima/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Imagem de cima')),
                ('link_image_cima', models.URLField(blank=True, help_text='Link da imagem de cima. Caso tiver, ao clicar na imagem será redirecionado para o local colocado.', max_length=255, verbose_name='Link da imagem de cima')),
                ('image_meio', models.ImageField(blank=True, help_text='Imagem que caso tiver, aparecerá abaixo do título, entre a descrição e o título.', upload_to='about/meio/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Imagem no meio')),
                ('link_image_meio', models.URLField(blank=True, help_text='Link da imagem do meio. Caso tiver, ao clicar na imagem será redirecionado para o local colocado.', max_length=255, verbose_name='Link da imagem do meio')),
                ('image_baixo', models.ImageField(blank=True, help_text='Imagem que caso tiver, aparecerá abaixo da descrição.', upload_to='about/baixo/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Imagem de baixo')),
                ('link_image_baixo', models.URLField(blank=True, help_text='Link de baixo. Caso tiver, ao clicar na imagem será redirecionado para o local colocado.', max_length=255, verbose_name='Link da imagem de baixo')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Título')),
                ('link_title', models.URLField(blank=True, help_text='Link do título. Caso tiver, ao clicar no título será redirecionado para o local colocado.', max_length=255, verbose_name='Link do título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('link_description', models.URLField(blank=True, help_text="Link da descrição. Caso tiver, ao clicar no texto padrão: 'Clique Aqui', será redirecionado para o local colocado.", max_length=255, verbose_name='Link da descrição')),
                ('text_link_description', models.CharField(blank=True, default='Clique Aqui', help_text="Texto em que ao clicar será redirecionado ao local dito no link da descrição. Padrão: 'Clique Aqui'.", max_length=255, verbose_name='Texto para clicar')),
                ('last', models.BooleanField(default=False, help_text='Adiciona uma quebra no final, para que os próximos sejam em baixo.', verbose_name='Último da linha?')),
            ],
            options={
                'verbose_name': 'Sobre',
                'verbose_name_plural': 'Sobre',
                'ordering': ('position', 'created'),
                'constraints': [models.UniqueConstraint(fields=('position',), name='unique_position_about')],
            },
        ),
    ]
