# Generated by Django 5.1.3 on 2024-11-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status_changed',
        ),
        migrations.AddField(
            model_name='item',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Nome do produto'),
        ),
        migrations.AddField(
            model_name='item',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando pagamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Pedido cancelado')], default='aguardando', max_length=50, verbose_name='Estado do pedido'),
        ),
    ]
