# Generated by Django 5.1.3 on 2024-11-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_item_product_name_remove_item_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_price',
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Slug do produto'),
        ),
    ]
