# Generated by Django 5.1 on 2024-09-22 12:43

import autoslug.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Imagem')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('is_available', models.BooleanField(default=True, verbose_name='Está disponível?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('starts_at', models.DateTimeField(verbose_name='Data do começo')),
                ('expires_at', models.DateTimeField(verbose_name='Data do fim')),
                ('status', models.CharField(choices=[('Expirado', 'Expirado'), ('Ativo', 'Ativo'), ('Pendente', 'Pendente')], default='Expirado', max_length=10, verbose_name='Estado')),
                ('changed_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço em promoção')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço original')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='products.product', to_field='slug', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'promoção',
                'verbose_name_plural': 'promoções',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('units', models.PositiveIntegerField(default=0, help_text='Quantidade disponível no estoque.', verbose_name='Unidades em estoque')),
                ('units_sold', models.PositiveIntegerField(default=0, help_text='Quantidade de unidades vendidas.', verbose_name='Quantidade vendida')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='products.product')),
            ],
            options={
                'verbose_name': 'estoque',
                'verbose_name_plural': 'estoques',
                'ordering': ('-created',),
            },
        ),
    ]
