# Generated by Django 5.1 on 2024-09-25 11:25

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('status', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('can_with_promotion', models.BooleanField(default=False, verbose_name='Pode ser usado com outra promoção?')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do desconto')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentagem de desconto')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='Limite de uso global')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Contagem de uso global')),
                ('user_usage_limit', models.PositiveIntegerField(default=1, verbose_name='Limite de uso por usuário')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Início da validade')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_codes', to='products.category', verbose_name='Categoria')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_codes', to='products.product', verbose_name='Produto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_codes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Código Promocional',
                'verbose_name_plural': 'Códigos Promocionais',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Usado em')),
                ('promotion_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.promotioncode', verbose_name='Código Promocional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Uso do Código Promocional',
                'verbose_name_plural': 'Usos de Códigos Promocionais',
                'unique_together': {('user', 'promotion_code')},
            },
        ),
    ]
