# Generated by Django 5.1.3 on 2024-11-11 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='role_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selling_roles', to='users.roletype'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.product', to_field='slug', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='promotioncode',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_codes', to='products.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='promotioncode',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_codes', to='products.product', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='promotioncode',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_codes', to='users.roletype', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='promotioncode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_codes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='promotioncodeusage',
            name='promotion_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.promotioncode', verbose_name='Código Promocional'),
        ),
        migrations.AddField(
            model_name='promotioncodeusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available'], name='products_pr_is_avai_c23034_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', False), ('role_type__isnull', True)), models.Q(('category__isnull', True), ('role_type__isnull', False)), _connector='OR'), name='category_or_role_type'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_role', True), ('role_type__isnull', False)), models.Q(('is_role', False), ('role_type__isnull', True)), _connector='OR'), name='role_type_consistency'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['product'], name='products_pr_product_6c2bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='promotioncode',
            index=models.Index(fields=['product'], name='products_pr_product_737e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='promotioncode',
            index=models.Index(fields=['category'], name='products_pr_categor_79dd1c_idx'),
        ),
        migrations.AddIndex(
            model_name='promotioncodeusage',
            index=models.Index(fields=['user'], name='products_pr_user_id_12a4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='promotioncodeusage',
            index=models.Index(fields=['promotion_code'], name='products_pr_promoti_61d560_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotioncodeusage',
            constraint=models.UniqueConstraint(fields=('user', 'promotion_code'), name='unique_payment_promotion_code'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product'], name='products_st_product_1e49b5_idx'),
        ),
    ]
