# Generated by Django 5.1.3 on 2024-11-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotioncodeusage',
            name='user_usage_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Contagem de uso por usuário'),
        ),
    ]
