# Generated by Django 5.1.3 on 2024-11-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_promotioncodeusage_user_usage_count'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='promotioncode',
            name='products_pr_categor_79dd1c_idx',
        ),
        migrations.RemoveField(
            model_name='promotioncode',
            name='category',
        ),
    ]
