# Generated by Django 5.1.3 on 2024-11-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_promotioncode_products_pr_categor_79dd1c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_name_9ff0a3_idx',
        ),
    ]
